spring:
  security:
    oauth2:
      client:
        registration:
          kakao:
            client-id: 5c2af632e5eb943eadbf20d0c4006bdb
            client-secret: x7TGPwsREQ44ndn3YoVQOberBwoPFbRE
            client-name: Kakao
            scope:
              - profile_nickname
              - profile_image
              - account_email
            authorization-grant-type: authorization_code
            redirect-uri: http://k8c101.p.ssafy.io:8000/user-service/login/oauth2/code/kakao
#            redirect-uri: http://localhost:8000/user-service/login/oauth2/code/kakao
            client-authentication-method: POST
        provider:
          kakao:
            authorization-uri: https://kauth.kakao.com/oauth/authorize
            token-uri: https://kauth.kakao.com/oauth/token
            user-info-uri: https://kapi.kakao.com/v2/user/me
            user-name-attribute: id
