server:
  # port 번호가 0번이면 랜덤으로 배정된다.
  port: 0

spring:
  application:
    name: user-service
  h2:
    console:
      enabled: true
      settings:
        web-allow-others: true
      path: /h2-console
  datasource:
#    url: jdbc:mysql://localhost:3306/seeyouagain?useSSL=false&allowPublicKeyRetrieval=true&serverTimezone=UTC
    url: jdbc:mysql://k8c101.p.ssafy.io:3307/seeyouagain?useSSL=false&allowPublicKeyRetrieval=true&serverTimezone=Asia/Seoul
    username: root
    password: seeyouagain1234
#    password: ssafy
    driver-class-name: com.mysql.cj.jdbc.Driver
  jpa:
    database: mysql
    database-platform: org.hibernate.dialect.MySQL5InnoDBDialect # 추가 해준 부분
    hibernate:
      ddl-auto: update
    show-sql: true
    generate-ddl: true
    properties:
      hibernate:
        default_batch_fetch_size: 500
  redis:
    lettuce:
      pool:
        min-idle: 0
        max-idle: 8
        max-active: 8
    port: 6379
    host: localhost
  profiles:
    include: oauth

eureka:
  instance:
    prefer-ip-address: true
    instance-id: ${spring.application.name}:${spring.application.instance_id:${random.value}}
  client:
    register-with-eureka: true
    fetch-registry: true
    service-url:
      defaultZone: http://127.0.0.1:8761/eureka

logging:
  level:
    com.example.userservice.client: DEBUG

gateway:
#    ip: 192.168.100.51
#  ip: 192.168.100.120
  ip: 172.18.0.7/16
#  ip: 192.168.0.100
#  ip: 172.20.10.2

product-service:
  ip: 172.18.0.8/16

chatting-service:
  ip: 172.18.0.10/16

token:
  secret: dyAeHubOOc8KaOfYB6XEQoEj1QzRlVgtjNL8PYs1A1tymZvvqkcEU7L1imkKHeDa

cloud:
  aws:
    s3:
      bucket: seeyouagain-s3-bucket
    stack.auto: false
    region.static: ap-northeast-2
    credentials:
      accessKey: AKIAZDX46XDEUXV5APLQ
      secretKey: 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
