server:
  port: 0

spring:
  application:
    name: chatting-service
  servlet:
    multipart:
      maxFileSize: 50MB
      maxRequestSize: 50MB
  h2:
    console:
      enabled: true
      settings:
        web-allow-others: true
      path: /h2-console
  datasource:
#    url: jdbc:mysql://localhost:3306/seeyouagain?useSSL=false&allowPublicKeyRetrieval=true&serverTimezone=Asia/Seoul
    url: jdbc:mysql://k8c101.p.ssafy.io:3309/seeyouagain?useSSL=false&allowPublicKeyRetrieval=true&serverTimezone=Asia/Seoul
    username: root
    password: seeyouagain1234
#    password: kp23156385@
    driver-class-name: com.mysql.cj.jdbc.Driver
  jpa:
    database: mysql
    database-platform: org.hibernate.dialect.MySQL8Dialect
    hibernate:
      ddl-auto: update
    show-sql: true
    generate-ddl: true

eureka:
  instance:
    prefer-ip-address: true
    instance-id: ${spring.application.name}:${spring.application.instance_id:${random.value}}
  client:
    register-with-eureka: true
    fetch-registry: true
    service-url:
      defaultZone: http://127.0.0.1:8761/eureka

logging:
  level:
    com.example.chattingservice.client: DEBUG

cloud:
  aws:
    s3:
      bucket: seeyouagain-s3-bucket
    stack.auto: false
    region.static: ap-northeast-2
    credentials:
      accessKey: 
      secretKey: 
